### ISSUE TITLE
Released egui 0.26

### ISSUE THREAD

**Issue by olehbozhok** [PingPongun/egui_struct#1]
Thanks for this excellent crate, I would be very appreciated if you update it to egui 0.26

**Comment by PingPongun** [comment]
I guess this will be simple version bump, I will check it and update crate tomorrow (cargo lacks sensible implementation of sth like `egui= ">=0.21, <0.27"`, so each egui major update requires issuing breaking release and dropping support for previous versions of egui, I do not find that elegant, so I was considering options to support multiple versions of egui and that's one of the reasons of delay here).

**Comment by olehbozhok** [comment]
Thanks for your response. Also, it is possible to have a library version the same as egui. Иut this is not an unambiguous question.

**Comment by PingPongun** [comment]
`egui_struct 0.4` with `egui 0.26` has been published
