### ISSUE TITLE
show_top fills width and hight completly; making design looking compact, but the rendering not integratable in layouts

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [PingPongun/egui_struct#2]
Hi there,

when i try to integrate the thing in my own widget, i do not find a suitable way to do any layouting. Everything to its right or bottom is just gone, since dispite its compact renering, the rect is full width and hight. I do not find any meaningful solution to determine meaningful the size to scale the rendering. What it the expected way to integrate the thing into a layout / vertical / horizonal or anything with neighbors?

**Comment by PingPongun** [comment]
One solution would be to use `ui.add_sized( [x,y], |ui| data.show_top(..) )`.
Another write own show_top, example (bellow example is taken from demo/src/app.rs):

```{Rust}
fn show_top_ow(
    data: &mut Data,
    ui: &mut egui::Ui,
    label: impl Into<egui::WidgetText> + Clone,
    reset2: Option<&Data>,
) -> egui::Response {
    let label: egui::WidgetText = label.into();
    let id = ui.make_persistent_id((label.text().to_string(), std::any::TypeId::of::<Data>()));
    egui::ScrollArea::vertical()
        .auto_shrink([true; 2]) // HERE differes from show_top(..)
        .show(ui, |ui| {
            egui::Grid::new(id)
                .striped(true)
                .num_columns(Data::COLUMN_COUNT)
                .show(ui, |ui| {
                    data.show_collapsing(ui, label, "", -1, Default::default(), reset2, id)
                })
                .inner
        })
        .inner
}
impl eframe::App for DemoApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        let Self { data } = self;
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.horizontal_top(|ui| {
                show_top_ow(data, ui, RichText::new("Data").heading(), None) | ui.button("test")
            })
        });
    }
}
```

 The problem is from ScrollArea shrinking configuration(pointed in above example). I will consider changing ScrollArea configuration in next release( or at least adding option to configure that).
I hope this helps (if I understood your problem correctly)

**Comment by cguentherTUChemnitz** [comment]
You are really great. You nailed it exactly with the code-snipped here. It seems the auto_shrink is exactly what i really was asking for. Thanks a lot for it.

In my eyes, this should be potentially the default. At least i was expecting to be able to layout the grid just next to other stuff, which was quite impossible without the auto_shrinking here.

**Comment by PingPongun** [comment]
I had changed `ScrollArea` behaviour in `show_top` to `egui`s default one (auto_shrink: true). `egui_struct v0.4` with that change has been published.
