### ISSUE TITLE
Initial collapse state for Vec fields

### ISSUE THREAD

**Issue by iMilchshake** [PingPongun/egui_struct#3]
Hi, this is such a nice library. I would love to use it for editing a large config struct at runtime. My config struct includes some Vecs that can be really large. Therefore it would be great if their fields could be collapsed by default.  Is there any way to do this already?

Otherwise, I believe an argument like this would be awesome:

```
#[eguis(collapsed = true)]
pub test_vec: Vec<usize>,
```

**Comment by PingPongun** [comment]
Hi, 
Sorry for late response (I missed notification).
I don't think there was a simple way to achieve this.
But I've just released v0.4.1 that adds (as You suggested) field level attribute (`#[eguis(start_collapsed = true)]`) that makes it possible to have field initially collapsed.
However, You may find it unnecessary, as I've also added, that collections (including Vec<>) are initially collapsed if they have more than 16 elements.

**Comment by iMilchshake** [comment]
Oh wow this is awesome! Thanks for the update :)
