### ISSUE TITLE
Compare with egui-probe

### ISSUE THREAD

**Issue by zakarumych** [PingPongun/egui_struct#4]
Hi!
This is neat library and nicely documented.

I wonder if you would be interested in adding comparison with my take on the same idea into README.
https://github.com/zakarumych/egui-probe

If not, you can just close the issue.

**Comment by PingPongun** [comment]
Hi! 
I've run demos from your crate, and it looks really nice (I've spotted one small bug on 90ec72c9fc10553fd776c121e0306888b58fbc49 — `maybe_boolen` when changed to `Some`, is impossible to revert to `None` state).

I think it's good idea to add your crate to comparison in Readme.
Could you add this through PR (I guess it would be preferable, as you have better understanding of yours crate's features)? If your crate has some features/advantages over my crate/other ones that are not already mentioned, do not hesitate to add new rows to the table.

**Comment by PingPongun** [comment]
I've added `egui-probe` to Readme
